import 'password_component.dart';

class WordSetComponent implements PasswordComponent {
  WordSetComponent() {
    _words = <String>[
      'Sunshine',
      'Dragon',
      'Banana',
      'Pizza',
      'Chocolate',
      'Rainbow',
      'Butterfly',
      'Sapphire',
      'Firefly',
      'Thunder',
      'Whisper',
      'Serenity',
      'Harmony',
      'Ocean',
      'Journey',
      'Galaxy',
      'Velvet',
      'Mystery',
      'Enigma',
      'Phoenix',
      'Aurora',
      'Infinity',
      'Dreamer',
      'Pumpkin',
      'Wonder',
      'Secret',
      'Miracle',
      'Legend',
      'Victory',
      'Champion',
      'Hero',
      'Warrior',
      'Warlock',
      'Wizard',
      'Mermaid',
      'Unicorn',
      'Pegasus',
      'Catalyst',
      'Lucky',
      'Spirit',
      'Passion',
      'Brave',
      'Courage',
      'Wisdom',
      'Eagle',
      'Tiger',
      'Lion',
      'Leopard',
      'Panther',
      'Jaguar',
      'Cheetah',
      'Gazelle',
      'Zebra',
      'Orchid',
      'Tulip',
      'Rose',
      'Lily',
      'Daisy',
      'Poppy',
      'Iris',
      'Carnation',
      'Peony',
      'Lotus',
      'Amethyst',
      'Emerald',
      'Ruby',
      'Sapphire',
      'Diamond',
      'Topaz',
      'Opal',
      'Pearl',
      'Amber',
      'Crystal',
      'Obsidian',
      'Onyx',
      'Quartz',
      'Garnet',
      'Turquoise',
      'Moonstone',
      'Sunstone',
      'Agate',
      'Citrine',
      'Malachite',
      'Peridot',
      'Lapis',
      'Jade',
      'Aquamarine',
      'Celestial',
      'Stardust',
      'Nebula',
      'Cosmos',
      'Supernova',
      'Eclipse',
      'Meteor',
      'Comet',
      'Starlight',
      'Asteroid',
      'Pluto',
      'Mars',
      'Venus',
      'Saturn',
      'Neptune',
      'Uranus',
      'Jupiter',
      'Mercury',
      'Earth',
    ];
  }

  late final List<String> _words;

  @override
  int get length => _words.length;

  @override
  String get(int index) {
    return _words.elementAt(index);
  }
}
